name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: install frontend dependencies
        run: pnpm install

      - name: Read release notes
        id: release_notes
        shell: pwsh
        run: |
          $body = Get-Content -Raw -Path "docs/RELEASE.md" -ErrorAction SilentlyContinue
          if (-not $body) { $body = "Release notes not found." }
          # Replace single quotes to avoid YAML quoting issues
          $body = $body -replace "'", "`'"
          $heredoc = "body<<EOF`n$body`nEOF"
          Add-Content -Path $env:GITHUB_OUTPUT -Value $heredoc

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: __VERSION__
          releaseName: "Release v__VERSION__"
          releaseBody: ${{ steps.release_notes.outputs.body }}
          releaseDraft: false
          prerelease: false
          includeDebug: false
          includeRelease: true
          includeUpdaterJson: true
